<?php
/**
 * Spanish Language File
 */
$lang = [
    // General
    'app_name' => 'Banco Mercantil',
    'welcome' => 'Bienvenido',
    'login' => 'Iniciar Sesión',
    'logout' => 'Cerrar Sesión',
    'save' => 'Guardar',
    'cancel' => 'Cancelar',
    'edit' => 'Editar',
    'delete' => 'Eliminar',
    'search' => 'Buscar',
    'back' => 'Volver',
    'actions' => 'Acciones',
    'confirm' => 'Confirmar',
    'success' => 'Éxito',
    'error' => 'Error',
    'warning' => 'Advertencia',
    'info' => 'Información',
    
    // Login
'login' => 'Iniciar Sesión',
'login_button_text' => 'Ingresar', 
'username' => 'Usuario',
'password' => 'Contraseña',
'forgot_password' => '¿Olvidaste tu contraseña?',
'fill_all_fields' => 'Por favor, complete todos los campos.',
'username_placeholder' => 'Ingrese su usuario...', 
'password_placeholder' => 'Ingrese su contraseña...',
    
    // Dashboard
    'dashboard' => 'Dashboard',
    'clients' => 'Clientes',
    'accounts' => 'Cuentas',
    'transactions' => 'Transacciones',
    'reports' => 'Reportes',
    'branches' => 'Oficinas',
    'total_clients' => 'Total de clientes',
    'total_accounts' => 'Total de cuentas',
    'today_transactions' => 'Transacciones hoy',
    'recent_transactions' => 'Transacciones Recientes',
    
    // Clients
    'new_client' => 'Nuevo Cliente',
'client_list' => 'Lista de Clientes',
'client_details' => 'Detalles del Cliente',
'edit_client' => 'Editar Cliente',
'name' => 'Nombre',
'paternal_last_name' => 'Apellido Paterno',
'maternal_last_name' => 'Apellido Materno',
'id_number' => 'Cédula de Identidad',
'address' => 'Dirección',
'phone' => 'Teléfono',
'email' => 'Correo Electrónico',
'birth_date' => 'Fecha de Nacimiento',
'branch' => 'Oficina',
'personal_information' => 'Información Personal',
'contact_information' => 'Información de Contacto',
'select_option' => 'Seleccione una opción',
'name_required' => 'El nombre es requerido',
'paternal_last_name_required' => 'El apellido paterno es requerido',
'id_number_required' => 'La cédula de identidad es requerida',
'branch_required' => 'La oficina es requerida',
'valid_email_required' => 'Ingrese un correo electrónico válido',
'client_saved' => 'Cliente guardado exitosamente',
'client_save_error' => 'Error al guardar el cliente',
'client_updated' => 'Cliente actualizado exitosamente',
'client_update_error' => 'Error al actualizar el cliente',
'client_deleted' => 'Cliente eliminado exitosamente',
'client_delete_error' => 'Error al eliminar el cliente',
'client_id_not_specified' => 'ID de cliente no especificado',
'client_not_found' => 'Cliente no encontrado',
'ci_already_exists' => 'Ya existe un cliente con esta cédula de identidad',
'no_clients' => 'No hay clientes registrados',
'all_fields_required' => 'Todos los campos marcados con * son requeridos',
    
   'account_list' => 'Lista de Cuentas',
'new_account' => 'Nueva Cuenta',
'account_details' => 'Detalles de Cuenta',
'edit_account' => 'Editar Cuenta',
'account_number' => 'Número de Cuenta',
'account_type' => 'Tipo de Cuenta',
'savings_account' => 'Cuenta de Ahorro',
'checking_account' => 'Cuenta Corriente',
'currency' => 'Moneda',
'bolivianos' => 'Bolivianos',
'dollars' => 'Dólares',
'balance' => 'Saldo',
'opening_date' => 'Fecha de Apertura',
'status' => 'Estado',
'active' => 'Activa',
'inactive' => 'Inactiva',
'account_information' => 'Información de la Cuenta',
'client_information' => 'Información del Cliente',
'initial_balance' => 'Saldo Inicial',
'initial_balance_help' => 'El saldo inicial con el que se creará la cuenta. Puede ser 0.',
'select_client' => 'Seleccionar Cliente',
'client_required' => 'El cliente es requerido',
'account_type_required' => 'El tipo de cuenta es requerido',
'currency_required' => 'La moneda es requerida',
'status_required' => 'El estado es requerido',
'account_saved' => 'Cuenta guardada exitosamente',
'account_save_error' => 'Error al guardar la cuenta',
'account_updated' => 'Cuenta actualizada exitosamente',
'account_update_error' => 'Error al actualizar la cuenta',
'account_closed' => 'Cuenta cerrada exitosamente',
'account_close_error' => 'Error al cerrar la cuenta',
'account_reactivated' => 'Cuenta reactivada exitosamente',
'account_reactivation_error' => 'Error al reactivar la cuenta',
'account_id_not_specified' => 'ID de cuenta no especificado',
'account_not_found' => 'Cuenta no encontrada',
'close_account' => 'Cerrar Cuenta',
'reactivate_account' => 'Reactivar Cuenta',
'confirm_close_account' => '¿Está seguro que desea cerrar esta cuenta? No se podrán realizar más transacciones hasta que se reactive.',
'confirm_reactivate_account' => '¿Está seguro que desea reactivar esta cuenta?',
'account_already_closed' => 'La cuenta ya está cerrada',
'account_already_active' => 'La cuenta ya está activa',
'no_accounts' => 'No hay cuentas registradas',
'view_client_details' => 'Ver detalles del cliente',
'account_statement' => 'Estado de Cuenta',
'statement_details' => 'Detalles del Estado',
'filter' => 'Filtrar',
'current_balance' => 'Saldo Actual',
'transactions_summary' => 'Resumen de Transacciones',
'transactions_list' => 'Lista de Transacciones',
'no_transactions_for_period' => 'No hay transacciones para el período seleccionado',
'print' => 'Imprimir',
'deposits' => 'Depósitos',
'withdrawals' => 'Retiros',
'transfers_received' => 'Transferencias Recibidas',
'transfers_sent' => 'Transferencias Enviadas',
'other' => 'Otro',
'initial_deposit' => 'Depósito Inicial',
'negative_balance_not_allowed' => 'No se permite un saldo inicial negativo',
'transfer' => 'Transferencia',
'transfer_sent' => 'Transferencia Enviada',
'transfer_received' => 'Transferencia Recibida',
    
    // Transactions
    'new_transaction' => 'Nueva Transacción',
    'transaction_list' => 'Lista de Transacciones',
    'transaction_id' => 'ID Transacción',
    'transaction_type' => 'Tipo de Transacción',
    'deposit' => 'Depósito',
    'withdrawal' => 'Retiro',
    'amount' => 'Monto',
    'date' => 'Fecha',
    'time' => 'Hora',
    'description' => 'Descripción',
    'transaction_details' => 'Detalles de la Transacción',
    'transaction_saved' => 'Transacción realizada exitosamente',
    'insufficient_funds' => 'Fondos insuficientes para realizar esta operación',
    'select_account' => 'Seleccionar Cuenta',
    'transaction_history' => 'Historial de Transacciones',
    'start_date' => 'Fecha Inicial',
    'end_date' => 'Fecha Final',
    'generate_report' => 'Generar Reporte',
    'print' => 'Imprimir',
    // Transacciones
'transaction_list' => 'Lista de Transacciones',
'transaction_details' => 'Detalles de Transacción',
'search_transactions' => 'Buscar Transacciones',
'transaction_receipt' => 'Comprobante de Transacción',
'deposit_funds' => 'Depositar Fondos',
'withdraw_funds' => 'Retirar Fondos',
'transfer_funds' => 'Transferir Fondos',
'deposit' => 'Depósito',
'withdrawal' => 'Retiro',
'transfer' => 'Transferencia',
'transfer_sent' => 'Transferencia Enviada',
'transfer_received' => 'Transferencia Recibida',
'other' => 'Otro',
'amount' => 'Monto',
'description' => 'Descripción',
'date' => 'Fecha',
'time' => 'Hora',
'account_number' => 'Número de Cuenta',
'client' => 'Cliente',
'actions' => 'Acciones',
'search' => 'Buscar',
'view' => 'Ver',
'receipt' => 'Comprobante',
'print_receipt' => 'Imprimir Comprobante',
'enter_account_number_to_deposit' => 'Ingrese el número de cuenta donde desea realizar el depósito.',
'enter_account_number_to_withdraw' => 'Ingrese el número de cuenta de donde desea realizar el retiro.',
'select_source_account' => 'Seleccione la cuenta de origen para la transferencia.',
'select_destination_account' => 'Seleccione la cuenta de destino para la transferencia.',
'source_account_number' => 'Número de Cuenta de Origen',
'destination_account_number' => 'Número de Cuenta de Destino',
'amount_required' => 'El monto es requerido',
'account_number_required' => 'El número de cuenta es requerido',
'missing_required_fields' => 'Faltan campos requeridos',
'invalid_amount' => 'Monto inválido',
'account_not_found' => 'Cuenta no encontrada',
'inactive_account_error' => 'La cuenta está inactiva',
'update_balance_error' => 'Error al actualizar el saldo',
'transaction_error' => 'Error al procesar la transacción',
'deposit_success' => 'Depósito realizado exitosamente',
'withdrawal_success' => 'Retiro realizado exitosamente',
'transfer_success' => 'Transferencia realizada exitosamente',
'insufficient_funds' => 'Fondos insuficientes',
    
    // Offices
    'new_office' => 'Nueva Oficina',
    'office_list' => 'Lista de Oficinas',
    'office_id' => 'ID Oficina',
    'office_name' => 'Nombre de Oficina',
    'central_office' => 'Oficina Central',
    'branch_office' => 'Agencia',
    'office_details' => 'Detalles de la Oficina',
    'office_saved' => 'Oficina guardada exitosamente',
    'office_updated' => 'Oficina actualizada exitosamente',
    'office_deleted' => 'Oficina eliminada exitosamente',
    
    // ATM
    'atm' => 'Cajero Automático',
    'atm_id' => 'ID Cajero',
    'location' => 'Ubicación',
    'atm_transaction' => 'Transacción en Cajero',
    
    // Cards
    'cards' => 'Tarjetas',
    'card_number' => 'Número de Tarjeta',
    'expiration_date' => 'Fecha de Expiración',
    'cvv' => 'CVV',
    'pin' => 'PIN',
    
    // Errors
    'page_not_found' => 'Página no encontrada',
    'access_denied' => 'Acceso denegado',
    'session_expired' => 'Su sesión ha expirado, por favor inicie sesión nuevamente',
    'system_error' => 'Error en el sistema, por favor intente nuevamente más tarde',
    
    // Reportes
    'transactions_by_date' => 'Transacciones por Fecha',
    'transactions_by_date_desc' => 'Reporte de todas las transacciones realizadas en un rango de fechas específico.',
    'transactions_by_client' => 'Transacciones por Cliente',
    'transactions_by_client_desc' => 'Reporte de todas las transacciones realizadas por un cliente específico.',
    'atm_statistics' => 'Estadísticas de ATM',
    'atm_statistics_desc' => 'Reporte de estadísticas de uso de cajeros automáticos.',
    'balances_by_branch' => 'Saldos por Oficina',
    'balances_by_branch_desc' => 'Reporte de saldos totales administrados por cada oficina.',
    'search_criteria' => 'Criterios de Búsqueda',
    'select_atm' => 'Seleccionar ATM',
    'select_option' => 'Seleccione una opción',
    'view_report' => 'Ver Reporte',
    'results' => 'Resultados',
    'close' => 'Cerrar',
    'period' => 'Período',
    'total_transactions' => 'Total de Transacciones',
    'total_deposits' => 'Total de Depósitos',
    'total_withdrawals' => 'Total de Retiros',
    'no_transactions_found' => 'No se encontraron transacciones para los criterios seleccionados.',
    'withdrawals' => 'Retiros',
    'deposits' => 'Depósitos',
    'withdrawal_amount' => 'Monto de Retiros',
    'deposit_amount' => 'Monto de Depósitos',
    'totals' => 'Totales',
    'clients_and_accounts_by_branch' => 'Clientes y Cuentas por Oficina',
    'view' => 'Ver',
    'no_transactions' => 'No hay transacciones recientes.',
    
    // Bienvenida
    'welcome_message_title' => 'Sistema Integral de Gestión Bancaria',
    'welcome_message' => 'Bienvenido al Sistema Banco Mercantil. Esta plataforma le permite gestionar de manera eficiente todas las operaciones bancarias, incluyendo la administración de clientes, cuentas, transacciones y reportes.',
    'quick_access' => 'Acceso Rápido',
    'home' => 'Inicio',
    'total_balance_bolivianos' => 'Saldo Total (Bs.)',
    'total_balance_dollars' => 'Saldo Total ($)',
    'view_all_transactions' => 'Ver todas las transacciones',
    'last_update' => 'Última actualización',
    'about' => 'Acerca de',
    'about_description' => 'Sistema bancario desarrollado para Banco Mercantil que permite la gestión integral de clientes, cuentas y transacciones financieras.',
    'system_information' => 'Información del Sistema',
    'version' => 'Versión',
    'developer' => 'Desarrollador',
    'features' => 'Características',
    'client_management' => 'Gestión de clientes',
    'account_management' => 'Administración de cuentas',
    'transaction_processing' => 'Procesamiento de transacciones',
    'reporting_system' => 'Sistema de reportes',
    'multilanguage_support' => 'Soporte multiidioma',
    'pwa_compatibility' => 'Compatibilidad con PWA',
    'back_to_home' => 'Volver al inicio'
];
?>